### PR TITLE
Add support for special keys

### PR DESCRIPTION
**Pull request by pmccarren**
Keys such as:
Return
Space
Tab
Arrow keys
Shift

### CODE REVIEW

**Comment by jkup** [comment]
I'm a little torn on this. I love the idea of having this support but I worry a bit about hijacking keys that already have expected behavior from the browser. I think people expect backspace to go back a page, the arrows to scroll, etc. What do you think? I'm just worried that hijacking common keys could have a negative effect on how accessible a site or app is.

**Comment by pmccarren** [comment]
Very good point! I have a few ideas that will keep all existing behavior intact. I'll implement them as soon as I have time!

**Comment by jkup** [comment]
Awesome, thanks!

**Comment by jkup** [comment]
Let's circle back to this!

**Pull request closed without merging**
